# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-linux:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - checkout
      - run:
          name: install roswell
          command: curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
      - run:
          name: set path
          command: echo "export PATH=$LISP_IMPLS_BIN:$PATH" >> $BASH_ENV

      - run:
          name: build-ros
          command: ros run -- --version

      - run:
          name: build-clisp
          command: ros install ccl-bin

      - run:
          name: install testing framework
          command: |
            ros install hu.dwim.stefil
            ros install cl-coveralls
#Project Settings>Environment Variables>COVERALLS_REPO_TOKEN
      - run:
          name: init test
          command: |
            ros init test
            cat >> test.ros \<< EOF
            (require :cl-coveralls)
            (defun main (&rest argv)
              (declare (ignore argv))
              (coveralls:with-coveralls (:exclude (list "t"))
                (or (asdf:test-system :local-time)
                  (uiop:quit -1))))
            EOF

      - run:
          name: run-sbcl
          command: |
            ros config set default.lisp sbcl-bin
            COVERALLS=true ./test.ros

      - run:
          name: run-clisp
          command: |
            ros config set default.lisp ccl-bin
            ./test.ros


  build-win:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: install scoop
          command:  |
            $ProgressPreference = "SilentlyContinue" # to solve iwr : Win32 internal error "Access is denied" 0x5 occurred while reading the console output buffer.
            iwr -useb get.scoop.sh | iex
      - run:
          name: install roswell
          command:  |
            $ProgressPreference = "SilentlyContinue"
            scoop install roswell
      - run:
          name: install testing framework
          command: ros install hu.dwim.stefil
      - run: |
          ros init test
          $String1 = @"
          (defun main (&rest argv)
            (declare (ignore argv))
            (push "C:/Users/circleci/project"
              ql:*local-project-directories*)
            (asdf:test-system :ci-test))
          "@
          Add-Content "test.ros" $String1
      - run:
          name: run-sbcl
          command: ros -- test.ros
#          command: COVERALLS=true ./test.ros
workflows:
  build_and_test:
    jobs:
      - build-linux
      - build-win


